/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sa_dsp_Compressor */

#ifndef _Included_sa_dsp_Compressor
#define _Included_sa_dsp_Compressor
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jlong JNICALL Java_sa_dsp_Compressor_newCompressor
  (JNIEnv *env, jclass clazz);

JNIEXPORT void JNICALL Java_sa_dsp_Compressor_setThresh
  (JNIEnv *env, jclass clazz, jlong obj, jdouble dB);

JNIEXPORT jdouble JNICALL Java_sa_dsp_Compressor_getThresh
  (JNIEnv *env, jclass clazz, jlong obj);

JNIEXPORT void JNICALL Java_sa_dsp_Compressor_setRatio
  (JNIEnv *env, jclass clazz, jlong obj, jdouble dB);

JNIEXPORT jdouble JNICALL Java_sa_dsp_Compressor_getRatio
  (JNIEnv *env, jclass clazz, jlong obj);

JNIEXPORT void JNICALL Java_sa_dsp_Compressor_initRuntime
  (JNIEnv *env, jclass clazz, jlong obj);

JNIEXPORT void JNICALL Java_sa_dsp_Compressor_processCompressorMono
  (JNIEnv *env, jclass clazz, jlong obj, jint bufferSize,
		  jshortArray pcm);

JNIEXPORT void JNICALL Java_sa_dsp_Compressor_processCompressorStereo
  (JNIEnv *env, jclass clazz, jlong obj, jint bufferSize,
		  jshortArray pcmLeft, jshortArray pcmRight);
#ifdef __cplusplus
}
#endif
#endif
