/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sa_dsp_Gate */

#ifndef _Included_sa_dsp_Gate
#define _Included_sa_dsp_Gate
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jlong JNICALL Java_sa_dsp_Gate_newGate
  (JNIEnv *env, jclass clazz);

JNIEXPORT void JNICALL Java_sa_dsp_Gate_setThresh
  (JNIEnv *env, jclass clazz, jlong obj, jdouble dB);

JNIEXPORT jdouble JNICALL Java_sa_dsp_Gate_getThresh
  (JNIEnv *env, jclass clazz, jlong obj);

JNIEXPORT void JNICALL Java_sa_dsp_Gate_initRuntime
  (JNIEnv *env, jclass clazz, jlong obj);

JNIEXPORT void JNICALL Java_sa_dsp_Gate_processGate
  (JNIEnv *env, jclass clazz, jlong obj, jint bufferSize,
		  jshortArray pcm);
#ifdef __cplusplus
}
#endif
#endif
